<a href="https://colab.research.google.com/github/ondalnight/Bigdata/blob/main/code/06w_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

dates = pd.date_range("2026-04-08", periods = 6)
dates

DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
               '2026-04-12', '2026-04-13'],
              dtype='datetime64[ns]', freq='D')

In [2]:
dates = pd.date_range("2026-04-08", end = "20260420")

In [3]:
dates = pd.date_range("2026-04-08", periods = 6, freq = '3H')
dates

/tmp/ipykernel_10379/1256832577.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range("2026-04-08", periods = 6, freq = '3H')

DatetimeIndex(['2026-04-08 00:00:00', '2026-04-08 03:00:00',
               '2026-04-08 06:00:00', '2026-04-08 09:00:00',
               '2026-04-08 12:00:00', '2026-04-08 15:00:00'],
              dtype='datetime64[ns]', freq='3h')

In [4]:
dates = pd.date_range("2026-04-08", periods = 6, freq = 'D')
dates

DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
               '2026-04-12', '2026-04-13'],
              dtype='datetime64[ns]', freq='D')

In [5]:
dates = pd.date_range("2026-04-08", periods = 6, freq = 'W')
dates

DatetimeIndex(['2026-04-12', '2026-04-19', '2026-04-26', '2026-05-03',
               '2026-05-10', '2026-05-17'],
              dtype='datetime64[ns]', freq='W-SUN')

In [6]:
dates = pd.date_range("2026-04-08", periods = 6, freq = 'W-SUN')
dates

DatetimeIndex(['2026-04-12', '2026-04-19', '2026-04-26', '2026-05-03',
               '2026-05-10', '2026-05-17'],
              dtype='datetime64[ns]', freq='W-SUN')

In [7]:
dates = pd.date_range("2026-04-08", periods = 6, freq = 'MS')
dates

DatetimeIndex(['2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01',
               '2026-09-01', '2026-10-01'],
              dtype='datetime64[ns]', freq='MS')

In [8]:
df2 = pd.DataFrame({
    "A" : 1.0,
    "B" : pd.Timestamp("20260302"),
    "C" : pd.Series(np.arange(1, 3, .5)),
    "D" : np.array([3] * 4, dtype = "int32"),
    "E" : pd.Categorical(["test", "train","test","train"]),
    "F" : "foo"
})

In [9]:
df3 = pd.DataFrame({
    "A" : [1.0, 2.0],
    "B" : pd.Timestamp("20260302"),
    "C" : pd.Series(np.arange(1, 3, .5)),
    "D" : np.array([3] * 4, dtype = "int32"),
    "E" : pd.Categorical(["test", "train","test","train"]),
    "F" : "foo"
})

ValueError: All arrays must be of the same length

In [ ]:
df4 = pd.DataFrame({
    "A" : 1.0,
    "B" : pd.Timestamp("20260302"),
    "C" : pd.Series(np.arange(1, 3, .5)),
    "D" : np.array([3] * 4, dtype = "int32"),
    "E" : pd.Categorical(["test", "train","test","train"]),
    "F" : "foo"
})

In [ ]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희','홍소희','유한빈','신수빈'],
                  columns = ['중간','기말','과제','출석'])

In [ ]:
pf['중간']

In [ ]:
pf.중간

In [ ]:
pf['출석']

In [ ]:
pf[['출석']]

In [ ]:
pf[['기말','출석','중간']]

In [ ]:
pf[['기말']]

In [ ]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희','홍소희','유한빈','신수빈'],
                  columns = ['중간','기말','과제','출석'])

In [ ]:
pf['중간'] > 20

In [ ]:
pf[pf['중간'] > 20]

In [ ]:
pf[pf['출석'] >= 19]

In [ ]:
pf[(pf['출석'] >= 19) & (pf['기말'] > 20)]

In [ ]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희','홍소희','유한빈','신수빈'],
                  columns = ['중간','기말','과제','출석'])

pf

In [ ]:
pf.loc[pf.index[0]]

In [ ]:
pf.loc[[pf.index[0]]]

In [ ]:
pf.loc[pf.index[1:4]]

In [ ]:
pf.loc[pf.index[1:4]][['기말','과제']]

In [ ]:
pf.loc[:, '과제']

In [ ]:
pf.loc[:,'중간':'과제']

In [ ]:
pf.loc[:, ['기말', '출석']]

In [ ]:
pf.loc[:, pf.columns[0]]

In [ ]:
pf.loc[:, [pf.columns[0]]]

In [ ]:
pf.loc[:, pf.columns[1:]]

In [ ]:
pf.loc[:, pf.columns[1:3]]

In [ ]:
pf.loc[:, pf.columns[1:]][['기말','과제']]

In [ ]:
pf.loc['윤일형','출석']

In [ ]:
pf.loc['윤일형':'유한빈','기말']

In [ ]:
pf.loc['윤일형':'유한빈', '기말':'과제']

In [ ]:
pf.loc[pf.index[0], pf.columns[1]]

In [ ]:
pf.loc[pf.index[0:3], pf.columns[2]]

In [ ]:
pf.loc[pf.index[0:3], pf.columns[2:]]

In [ ]:
pf.iloc[1]

In [ ]:
pf.iloc[[1]]

In [ ]:
pf.iloc[[1, 3]]

In [ ]:
pf.iloc[2:]

In [ ]:
pf.iloc[:, 2]

In [ ]:
pf.iloc[:, [2]]

In [ ]:
pf.iloc[:, 1:]

In [ ]:
pf.iloc[1,1]

In [ ]:
pf.iloc[1:3, 1:]

In [ ]:
pf.iloc[:, 1:]

In [ ]:
pf.iloc[[1,3,4],1:]

In [ ]:
pf.iloc[[1,3,4],[0,1]]

In [ ]:
pf.at['윤일형','과제']

In [ ]:
pf.at['유한빈','기말']

In [ ]:
pf.at[pf.index[1], '출석']

In [ ]:
pf.at[pf.index[3],pf.columns[2]]

In [ ]:
pf.iat[1,2]

In [ ]:
pf.iat[2,3]

In [ ]:
pf.loc[:, pf.columns[1:]] [['기말','과제']]

In [ ]:
pf2 = pf.loc[:, pf.columns[1:]]
pf2[['기말','과제']]

In [ ]:
pf2 = pf.iloc[:,1:]
pf2[['기말','과제']]

In [30]:
import os
print(os.listdir('/content/'))

['.config', '2016년졸음운전.csv', 'sample_data']

In [33]:
import pandas as pd
import os
import glob

# '2016'으로 시작하는 csv 파일을 찾아 첫 번째 파일을 선택합니다.
file_list = glob.glob('/content/2016*.csv')

if file_list:
    file_path = file_list[0]
    df = pd.read_csv(file_path, encoding='euc-kr', index_col=0)
    display(df)
else:
    print('파일을 찾을 수 없습니다. 업로드 상태를 확인해 주세요.')

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [35]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [37]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [38]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [39]:
df.cumsum()

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [40]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [41]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [42]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [43]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [48]:
from IPython.display import display_html

def display_side_by_side(*args):
    html_str = ''
    for df in args:
        html_str += df.to_html()
    display_html(html_str.replace('table', 'table style="display:inline"'), raw=True)

In [49]:
display_side_by_side(df, df.mean(axis=1).to_frame())

In [52]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)

df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [53]:
display_side_by_side(df, df2)

In [56]:
df2.sum()

사고(건)     7299
사망(명)      294
부상(명)    14697
재해자수     14991
dtype: int64

In [55]:
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         4866    196   9798  9994

In [58]:
df2.loc['총계'] = df2.sum()
df2

          사고(건)  사망(명)  부상(명)   재해자수
연월
2016년1월     192      5    387    392
2016년2월     174      6    328    334
2016년3월     217      7    435    442
2016년4월     216      7    419    426
2016년5월     239     13    522    535
2016년6월     200     12    362    374
2016년7월     227      9    460    469
2016년8월     230      7    490    497
2016년9월     187     13    347    360
2016년10월    183     10    367    377
2016년11월    200      5    418    423
2016년12월    168      4    364    368
총계         9732    392  19596  19988

In [59]:
df2 > 10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [60]:
df2[df2 > 10]

          사고(건)  사망(명)  부상(명)   재해자수
연월
2016년1월     192    NaN    387    392
2016년2월     174    NaN    328    334
2016년3월     217    NaN    435    442
2016년4월     216    NaN    419    426
2016년5월     239   13.0    522    535
2016년6월     200   12.0    362    374
2016년7월     227    NaN    460    469
2016년8월     230    NaN    490    497
2016년9월     187   13.0    347    360
2016년10월    183    NaN    367    377
2016년11월    200    NaN    418    423
2016년12월    168    NaN    364    368
총계         9732  392.0  19596  19988

In [61]:
df2[[True]*6 + [False]*7]

         사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

In [62]:
df2['재해자수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [63]:
df2[df2['재해자수'] > 400]

          사고(건)  사망(명)  부상(명)   재해자수
연월
2016년3월     217      7    435    442
2016년4월     216      7    419    426
2016년5월     239     13    522    535
2016년7월     227      9    460    469
2016년8월     230      7    490    497
2016년11월    200      5    418    423
총계         9732    392  19596  19988

In [64]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [65]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [66]:
df['사망(명)'].isin([7, 10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [67]:
df[df['사망(명)'].isin([7, 10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [68]:
df[df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [69]:
df3=df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [70]:
df3[df3 > 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

In [73]:
df = pd.DataFrame({'A':range(1,6),
                   'B':range(6,-3,-2),
                   'C':range(10,5,-1),
                   'D clmns':range(3,-2,-1),
                   'E': ['python','java','python','go','python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [74]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [75]:
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [76]:
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [77]:
df.query('A > 0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [78]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [80]:
df.query("E != 'python'")

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

In [81]:
df.query('A == "D clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [82]:
df.query('A > 3 | B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [83]:
df.query('A > 2 & C < 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [84]:
df.query("E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [85]:
num = 3
df.query('B > @num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [86]:
num = 3
df.query(f'B > {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [87]:
s = "E.str.contains('py')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [89]:
s = 'E.str.startswith("g")'
df.query(s)

   A  B  C  D clmns   E
3  4  0  7        0  go

In [90]:
s = "E.str.endswith('on')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python